import axios from 'axios'
import Head from 'next/head'
import HomeImage from '../components/HomeImage'
import MemoriesList from '../components/MemoriesList'
import Navbar from '../components/Navbar'

export default function Home({memories}) {
  console.log(memories)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <h1 style={{textAlign:"center"}}>Welcome to memories!</h1>
        <HomeImage />
        <MemoriesList memories={memories}/>
      </main>

    </div>
  )
}


export const getServerSideProps = async () =>{
  const res = await axios.get("https://memories-app-black.vercel.app/api/memorie")
  console.log(res)

  return {
    props:{
      memories:res.data
    }
  }
}